/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@stencil/router';
import '@stencil/state-tunnel';
import {
  MatchResults,
} from '@stencil/router';


export namespace Components {

  interface HamburgerMenu {}
  interface HamburgerMenuAttributes extends StencilHTMLAttributes {}

  interface KcLogo {}
  interface KcLogoAttributes extends StencilHTMLAttributes {}

  interface MlbLogo {}
  interface MlbLogoAttributes extends StencilHTMLAttributes {}

  interface AppHome {}
  interface AppHomeAttributes extends StencilHTMLAttributes {}

  interface AppProfile {
    'match': MatchResults;
  }
  interface AppProfileAttributes extends StencilHTMLAttributes {
    'match'?: MatchResults;
  }

  interface RoyalsRoot {}
  interface RoyalsRootAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'HamburgerMenu': Components.HamburgerMenu;
    'KcLogo': Components.KcLogo;
    'MlbLogo': Components.MlbLogo;
    'AppHome': Components.AppHome;
    'AppProfile': Components.AppProfile;
    'RoyalsRoot': Components.RoyalsRoot;
  }

  interface StencilIntrinsicElements {
    'hamburger-menu': Components.HamburgerMenuAttributes;
    'kc-logo': Components.KcLogoAttributes;
    'mlb-logo': Components.MlbLogoAttributes;
    'app-home': Components.AppHomeAttributes;
    'app-profile': Components.AppProfileAttributes;
    'royals-root': Components.RoyalsRootAttributes;
  }


  interface HTMLHamburgerMenuElement extends Components.HamburgerMenu, HTMLStencilElement {}
  var HTMLHamburgerMenuElement: {
    prototype: HTMLHamburgerMenuElement;
    new (): HTMLHamburgerMenuElement;
  };

  interface HTMLKcLogoElement extends Components.KcLogo, HTMLStencilElement {}
  var HTMLKcLogoElement: {
    prototype: HTMLKcLogoElement;
    new (): HTMLKcLogoElement;
  };

  interface HTMLMlbLogoElement extends Components.MlbLogo, HTMLStencilElement {}
  var HTMLMlbLogoElement: {
    prototype: HTMLMlbLogoElement;
    new (): HTMLMlbLogoElement;
  };

  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {}
  var HTMLAppProfileElement: {
    prototype: HTMLAppProfileElement;
    new (): HTMLAppProfileElement;
  };

  interface HTMLRoyalsRootElement extends Components.RoyalsRoot, HTMLStencilElement {}
  var HTMLRoyalsRootElement: {
    prototype: HTMLRoyalsRootElement;
    new (): HTMLRoyalsRootElement;
  };

  interface HTMLElementTagNameMap {
    'hamburger-menu': HTMLHamburgerMenuElement
    'kc-logo': HTMLKcLogoElement
    'mlb-logo': HTMLMlbLogoElement
    'app-home': HTMLAppHomeElement
    'app-profile': HTMLAppProfileElement
    'royals-root': HTMLRoyalsRootElement
  }

  interface ElementTagNameMap {
    'hamburger-menu': HTMLHamburgerMenuElement;
    'kc-logo': HTMLKcLogoElement;
    'mlb-logo': HTMLMlbLogoElement;
    'app-home': HTMLAppHomeElement;
    'app-profile': HTMLAppProfileElement;
    'royals-root': HTMLRoyalsRootElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
