/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@stencil/router';
import '@stencil/state-tunnel';


export namespace Components {

  interface RoyalsButton {
    'title': string;
    'type': string;
  }
  interface RoyalsButtonAttributes extends StencilHTMLAttributes {
    'title'?: string;
    'type'?: string;
  }

  interface RoyalsHome {}
  interface RoyalsHomeAttributes extends StencilHTMLAttributes {}

  interface HamburgerMenu {}
  interface HamburgerMenuAttributes extends StencilHTMLAttributes {}

  interface KcLogo {}
  interface KcLogoAttributes extends StencilHTMLAttributes {}

  interface MlbLogo {}
  interface MlbLogoAttributes extends StencilHTMLAttributes {}

  interface RoyalsPlayer {
    'player': any;
  }
  interface RoyalsPlayerAttributes extends StencilHTMLAttributes {
    'player'?: any;
  }

  interface RoyalsRoot {}
  interface RoyalsRootAttributes extends StencilHTMLAttributes {}

  interface RoyalsRoster {}
  interface RoyalsRosterAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'RoyalsButton': Components.RoyalsButton;
    'RoyalsHome': Components.RoyalsHome;
    'HamburgerMenu': Components.HamburgerMenu;
    'KcLogo': Components.KcLogo;
    'MlbLogo': Components.MlbLogo;
    'RoyalsPlayer': Components.RoyalsPlayer;
    'RoyalsRoot': Components.RoyalsRoot;
    'RoyalsRoster': Components.RoyalsRoster;
  }

  interface StencilIntrinsicElements {
    'royals-button': Components.RoyalsButtonAttributes;
    'royals-home': Components.RoyalsHomeAttributes;
    'hamburger-menu': Components.HamburgerMenuAttributes;
    'kc-logo': Components.KcLogoAttributes;
    'mlb-logo': Components.MlbLogoAttributes;
    'royals-player': Components.RoyalsPlayerAttributes;
    'royals-root': Components.RoyalsRootAttributes;
    'royals-roster': Components.RoyalsRosterAttributes;
  }


  interface HTMLRoyalsButtonElement extends Components.RoyalsButton, HTMLStencilElement {}
  var HTMLRoyalsButtonElement: {
    prototype: HTMLRoyalsButtonElement;
    new (): HTMLRoyalsButtonElement;
  };

  interface HTMLRoyalsHomeElement extends Components.RoyalsHome, HTMLStencilElement {}
  var HTMLRoyalsHomeElement: {
    prototype: HTMLRoyalsHomeElement;
    new (): HTMLRoyalsHomeElement;
  };

  interface HTMLHamburgerMenuElement extends Components.HamburgerMenu, HTMLStencilElement {}
  var HTMLHamburgerMenuElement: {
    prototype: HTMLHamburgerMenuElement;
    new (): HTMLHamburgerMenuElement;
  };

  interface HTMLKcLogoElement extends Components.KcLogo, HTMLStencilElement {}
  var HTMLKcLogoElement: {
    prototype: HTMLKcLogoElement;
    new (): HTMLKcLogoElement;
  };

  interface HTMLMlbLogoElement extends Components.MlbLogo, HTMLStencilElement {}
  var HTMLMlbLogoElement: {
    prototype: HTMLMlbLogoElement;
    new (): HTMLMlbLogoElement;
  };

  interface HTMLRoyalsPlayerElement extends Components.RoyalsPlayer, HTMLStencilElement {}
  var HTMLRoyalsPlayerElement: {
    prototype: HTMLRoyalsPlayerElement;
    new (): HTMLRoyalsPlayerElement;
  };

  interface HTMLRoyalsRootElement extends Components.RoyalsRoot, HTMLStencilElement {}
  var HTMLRoyalsRootElement: {
    prototype: HTMLRoyalsRootElement;
    new (): HTMLRoyalsRootElement;
  };

  interface HTMLRoyalsRosterElement extends Components.RoyalsRoster, HTMLStencilElement {}
  var HTMLRoyalsRosterElement: {
    prototype: HTMLRoyalsRosterElement;
    new (): HTMLRoyalsRosterElement;
  };

  interface HTMLElementTagNameMap {
    'royals-button': HTMLRoyalsButtonElement
    'royals-home': HTMLRoyalsHomeElement
    'hamburger-menu': HTMLHamburgerMenuElement
    'kc-logo': HTMLKcLogoElement
    'mlb-logo': HTMLMlbLogoElement
    'royals-player': HTMLRoyalsPlayerElement
    'royals-root': HTMLRoyalsRootElement
    'royals-roster': HTMLRoyalsRosterElement
  }

  interface ElementTagNameMap {
    'royals-button': HTMLRoyalsButtonElement;
    'royals-home': HTMLRoyalsHomeElement;
    'hamburger-menu': HTMLHamburgerMenuElement;
    'kc-logo': HTMLKcLogoElement;
    'mlb-logo': HTMLMlbLogoElement;
    'royals-player': HTMLRoyalsPlayerElement;
    'royals-root': HTMLRoyalsRootElement;
    'royals-roster': HTMLRoyalsRosterElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
