// export const royals = {
//   name: 'Royals',
//   market: 'Kansas City',
//   abbr: 'KC',
//   id: '833a51a9-0d84-410f-bd77-da08c3e5e26e',
//   venue: {
//     name: 'Kauffman Stadium',
//     market: 'Kansas City',
//     capacity: 37903,
//     surface: 'grass',
//     address: 'One Royal Way',
//     city: 'Kansas City',
//     state: 'MO',
//     zip: '64129',
//     country: 'USA',
//     id: '6fca95c9-7f2c-4acb-a9f3-02ef96340d2a',
//     field_orientation: 'NE',
//     stadium_type: 'outdoor'
//   },
//   league: {
//     alias: 'AL',
//     name: 'American League',
//     id: '2ea6efe7-2e21-4f29-80a2-0a24ad1f5f85'
//   },
//   division: {
//     alias: 'C',
//     name: 'Central',
//     id: '255fadc6-367e-4238-8ece-d0cddabf7d72'
//   },
//   staff: [
//     {
//       full_name: 'Terry Bradshaw',
//       first_name: 'Terry',
//       last_name: 'Bradshaw',
//       position: 'Hitting Coach',
//       id: '3d56bda6-5de7-47b1-9036-6be9003de7e1'
//     },
//     {
//       full_name: 'Ned Yost',
//       first_name: 'Ned',
//       last_name: 'Yost',
//       position: 'Manager',
//       id: '46ec4f4d-3b67-467c-9964-1b67c3f57533'
//     },
//     {
//       full_name: 'Cal Eldred',
//       first_name: 'Cal',
//       last_name: 'Eldred',
//       position: 'Pitching Coach',
//       id: 'f0b0df28-7767-451d-afd3-47002db2cad9'
//     }
//   ],
//   players: [
//     {
//       id: '5c76431a-9864-4a9d-90f4-3850a3b0b631',
//       status: 'A',
//       position: 'C',
//       primary_position: 'C',
//       first_name: 'Cameron',
//       last_name: 'Gallagher',
//       preferred_name: 'Cam',
//       jersey_number: '36',
//       full_name: 'Cam Gallagher',
//       mlbam_id: '595956',
//       height: '75',
//       weight: '230',
//       throw_hand: 'R',
//       bat_hand: 'R',
//       high_school: 'Manheim Township, Lancaster, PA',
//       birthdate: '1992-12-06',
//       birthstate: 'PA',
//       birthcountry: 'USA',
//       birthcity: 'Lancaster',
//       pro_debut: '2017-08-06',
//       updated: '2018-08-31T17:06:15+00:00',
//       active: true
//     },
//     {
//       id: '9baf07d4-b1cb-4494-8c95-600d9e8de1a9',
//       status: 'A',
//       position: 'C',
//       primary_position: 'C',
//       first_name: 'Salvador',
//       last_name: 'Pérez',
//       preferred_name: 'Salvador',
//       jersey_number: '13',
//       full_name: 'Salvador Pérez',
//       mlbam_id: '521692',
//       height: '76',
//       weight: '240',
//       throw_hand: 'R',
//       bat_hand: 'R',
//       birthdate: '1990-05-10',
//       birthcountry: 'VEN',
//       birthcity: 'Valencia',
//       pro_debut: '2011-08-10',
//       updated: '2019-01-30T22:10:43+00:00',
//       active: true
//     },
//     {
//       id: '8bda3557-0224-44f6-965f-b629a3f502c4',
//       status: 'A',
//       position: 'C',
//       primary_position: 'C',
//       first_name: 'Meibrys',
//       last_name: 'Viloria',
//       preferred_name: 'Meibrys',
//       jersey_number: '72',
//       full_name: 'Meibrys Viloria',
//       mlbam_id: '650619',
//       height: '71',
//       weight: '220',
//       throw_hand: 'R',
//       bat_hand: 'L',
//       birthdate: '1997-02-15',
//       birthcountry: 'COL',
//       birthcity: 'Cartagena',
//       pro_debut: '2018-09-02',
//       updated: '2018-12-20T17:35:15+00:00',
//       active: true
//     },
//     {
//       id: 'ac8ecb22-30e8-42d3-a5a9-ce8869ab4df5',
//       status: 'A',
//       position: 'IF',
//       primary_position: '3B',
//       first_name: 'Hunter',
//       last_name: 'Dozier',
//       preferred_name: 'Hunter',
//       jersey_number: '17',
//       full_name: 'Hunter Dozier',
//       mlbam_id: '641531',
//       height: '76',
//       weight: '220',
//       throw_hand: 'R',
//       bat_hand: 'R',
//       college: 'Stephen F. Austin State',
//       high_school: 'Denton',
//       birthdate: '1991-08-22',
//       birthstate: 'TX',
//       birthcountry: 'USA',
//       birthcity: 'Wichita Falls',
//       pro_debut: '2016-09-12',
//       updated: '2018-09-17T19:59:49+00:00',
//       active: true
//     },
//     {
//       id: '35c9311e-df13-4a6f-afb1-d8732398cd50',
//       status: 'A',
//       position: 'IF',
//       primary_position: '3B',
//       first_name: 'Kelvin',
//       last_name: 'Gutierrez',
//       preferred_name: 'Kelvin',
//       jersey_number: '75',
//       full_name: 'Kelvin Gutierrez',
//       mlbam_id: '642721',
//       height: '75',
//       weight: '215',
//       throw_hand: 'R',
//       bat_hand: 'R',
//       birthdate: '1994-08-28',
//       birthcountry: 'DOM',
//       birthcity: 'Pimentel',
//       updated: '2019-02-08T19:39:19+00:00',
//       active: true
//     },
//     {
//       id: '92500d32-2314-4c7c-91c5-110f95229f9a',
//       status: 'A',
//       position: 'IF',
//       primary_position: '2B',
//       first_name: 'Whitley',
//       last_name: 'Merrifield',
//       preferred_name: 'Whit',
//       jersey_number: '15',
//       full_name: 'Whit Merrifield',
//       mlbam_id: '593160',
//       height: '72',
//       weight: '195',
//       throw_hand: 'R',
//       bat_hand: 'R',
//       college: 'South Carolina',
//       high_school: 'Davie County',
//       birthdate: '1989-01-24',
//       birthstate: 'NC',
//       birthcountry: 'USA',
//       birthcity: 'Advance',
//       pro_debut: '2016-05-18',
//       updated: '2019-01-30T22:13:13+00:00',
//       active: true
//     },
//     {
//       id: 'dd1d9fc7-25af-4f36-a30f-3525a2ba4e50',
//       status: 'A',
//       position: 'IF',
//       primary_position: 'SS',
//       first_name: 'Raúl',
//       last_name: 'Mondesí',
//       preferred_name: 'Adalberto',
//       jersey_number: '27',
//       full_name: 'Adalberto Mondesí',
//       mlbam_id: '609275',
//       height: '73',
//       weight: '190',
//       throw_hand: 'R',
//       bat_hand: 'B',
//       birthdate: '1995-07-27',
//       birthstate: 'CA',
//       birthcountry: 'USA',
//       birthcity: 'Los Angeles',
//       pro_debut: '2015-10-30',
//       updated: '2019-01-30T22:14:13+00:00',
//       active: true
//     },
//     {
//       id: '95f62738-6fd7-48a0-b8a8-46f17c0f939c',
//       status: 'A',
//       position: 'IF',
//       primary_position: '1B',
//       first_name: 'Ryan',
//       last_name: "O'Hearn",
//       preferred_name: 'Ryan',
//       jersey_number: '66',
//       full_name: "Ryan O'Hearn",
//       mlbam_id: '656811',
//       height: '75',
//       weight: '200',
//       throw_hand: 'L',
//       bat_hand: 'L',
//       college: 'Sam Houston State',
//       high_school: 'Wakeland',
//       birthdate: '1993-07-26',
//       birthstate: 'TX',
//       birthcountry: 'USA',
//       birthcity: 'Frisco',
//       pro_debut: '2018-07-31',
//       updated: '2018-08-18T14:15:56+00:00',
//       active: true
//     },
//     {
//       id: '0e629c09-cd75-4b1f-89c5-7ed295d79a39',
//       status: 'A',
//       position: 'OF',
//       primary_position: 'RF',
//       first_name: 'Jorge',
//       last_name: 'Bonifacio',
//       preferred_name: 'Jorge',
//       jersey_number: '38',
//       full_name: 'Jorge Bonifacio',
//       mlbam_id: '593528',
//       height: '73',
//       weight: '225',
//       throw_hand: 'R',
//       bat_hand: 'R',
//       birthdate: '1993-06-04',
//       birthcountry: 'DOM',
//       birthcity: 'Santo Domingo',
//       pro_debut: '2017-04-21',
//       updated: '2019-01-30T22:14:59+00:00',
//       active: true
//     },
//     {
//       id: '37e4b478-edd6-49ad-85cc-75e31ea59f19',
//       status: 'A',
//       position: 'OF',
//       primary_position: 'CF',
//       first_name: 'Brian',
//       last_name: 'Goodwin',
//       preferred_name: 'Brian',
//       jersey_number: '25',
//       full_name: 'Brian Goodwin',
//       mlbam_id: '571718',
//       height: '72',
//       weight: '200',
//       throw_hand: 'R',
//       bat_hand: 'L',
//       college: 'Miami Dade College, FL',
//       high_school: 'Rocky Mount (NC)',
//       birthdate: '1990-11-02',
//       birthstate: 'NC',
//       birthcountry: 'USA',
//       birthcity: 'Rocky Mount',
//       pro_debut: '2016-08-06',
//       updated: '2019-01-30T22:15:30+00:00',
//       active: true
//     },
//     {
//       id: '1018c599-6053-4ed9-8952-b0e9a1519677',
//       status: 'A',
//       position: 'OF',
//       primary_position: 'LF',
//       first_name: 'Alex',
//       last_name: 'Gordon',
//       preferred_name: 'Alex',
//       jersey_number: '4',
//       full_name: 'Alex Gordon',
//       mlbam_id: '460086',
//       height: '73',
//       weight: '225',
//       throw_hand: 'R',
//       bat_hand: 'L',
//       college: 'Nebraska',
//       high_school: 'Lincoln Southeast, Lincoln, NE',
//       birthdate: '1984-02-10',
//       birthstate: 'NE',
//       birthcountry: 'USA',
//       birthcity: 'Lincoln',
//       pro_debut: '2007-04-02',
//       updated: '2019-01-30T22:16:12+00:00',
//       active: true
//     },
//     {
//       id: '2b54473f-8ad3-4aa1-8e26-33d98d07fca4',
//       status: 'A',
//       position: 'OF',
//       primary_position: 'LF',
//       first_name: 'Terrance',
//       last_name: 'Gore',
//       preferred_name: 'Terrance',
//       jersey_number: '0',
//       full_name: 'Terrance Gore',
//       mlbam_id: '605253',
//       height: '67',
//       weight: '165',
//       throw_hand: 'R',
//       bat_hand: 'R',
//       college: 'Gulf Coast State CC, FL',
//       high_school: 'Jones County, Gray, GA',
//       birthdate: '1991-06-08',
//       birthstate: 'GA',
//       birthcountry: 'USA',
//       birthcity: 'Macon',
//       pro_debut: '2014-08-31',
//       updated: '2018-12-18T20:06:15+00:00',
//       active: true
//     },
//     {
//       id: '090ff436-c1e8-4927-b457-355cf4f9993b',
//       status: 'A',
//       position: 'OF',
//       primary_position: 'CF',
//       first_name: 'Billy',
//       last_name: 'Hamilton',
//       preferred_name: 'Billy',
//       jersey_number: '6',
//       full_name: 'Billy Hamilton',
//       mlbam_id: '571740',
//       height: '72',
//       weight: '160',
//       throw_hand: 'R',
//       bat_hand: 'B',
//       high_school: 'Taylorsville, MS',
//       birthdate: '1990-09-09',
//       birthstate: 'MS',
//       birthcountry: 'USA',
//       birthcity: 'Collins',
//       pro_debut: '2013-09-03',
//       updated: '2019-02-08T19:39:28+00:00',
//       active: true
//     },
//     {
//       id: '3e39fe20-6dca-4894-807b-1ce76ff93e29',
//       status: 'A',
//       position: 'OF',
//       primary_position: 'RF',
//       first_name: 'Christopher',
//       last_name: 'Owings',
//       preferred_name: 'Chris',
//       jersey_number: '2',
//       full_name: 'Chris Owings',
//       mlbam_id: '572008',
//       height: '70',
//       weight: '185',
//       throw_hand: 'R',
//       bat_hand: 'R',
//       high_school: 'Gilbert, SC',
//       birthdate: '1991-08-12',
//       birthstate: 'SC',
//       birthcountry: 'USA',
//       birthcity: 'Charleston',
//       pro_debut: '2013-09-03',
//       updated: '2019-02-08T19:39:58+00:00',
//       active: true
//     },
//     {
//       id: '1ec2eeb7-01f2-428d-a9bf-8ffb9178759f',
//       status: 'A',
//       position: 'OF',
//       primary_position: 'CF',
//       first_name: 'Brett',
//       last_name: 'Phillips',
//       preferred_name: 'Brett',
//       jersey_number: '14',
//       full_name: 'Brett Phillips',
//       mlbam_id: '621433',
//       height: '72',
//       weight: '185',
//       throw_hand: 'R',
//       bat_hand: 'L',
//       high_school: 'Seminole, FL',
//       birthdate: '1994-05-30',
//       birthstate: 'FL',
//       birthcountry: 'USA',
//       birthcity: 'Seminole',
//       pro_debut: '2017-06-05',
//       updated: '2018-09-16T16:41:16+00:00',
//       active: true
//     },
//     {
//       id: '4eba23e5-b274-4a2b-a3c7-fe2009a90619',
//       status: 'A',
//       position: 'OF',
//       primary_position: 'RF',
//       first_name: 'Jorge',
//       last_name: 'Soler',
//       preferred_name: 'Jorge',
//       jersey_number: '12',
//       full_name: 'Jorge Soler',
//       mlbam_id: '624585',
//       height: '76',
//       weight: '230',
//       throw_hand: 'R',
//       bat_hand: 'R',
//       birthdate: '1992-02-25',
//       birthcountry: 'CUB',
//       birthcity: 'Havana',
//       pro_debut: '2014-08-27',
//       updated: '2019-01-30T22:18:04+00:00',
//       active: true
//     },
//     {
//       id: 'b7b19f8d-e715-4b66-ab11-428544faf023',
//       status: 'A',
//       position: 'P',
//       primary_position: 'RP',
//       first_name: 'Scott',
//       last_name: 'Barlow',
//       preferred_name: 'Scott',
//       jersey_number: '58',
//       full_name: 'Scott Barlow',
//       mlbam_id: '605130',
//       height: '75',
//       weight: '215',
//       throw_hand: 'R',
//       bat_hand: 'R',
//       high_school: 'Golden Valley, Santa Clarita, CA',
//       birthdate: '1992-12-18',
//       birthstate: 'CT',
//       birthcountry: 'USA',
//       birthcity: 'New London',
//       pro_debut: '2018-04-30',
//       updated: '2018-10-02T22:21:10+00:00',
//       active: true
//     },
//     {
//       id: '6d3c33e8-1ef8-4f53-b5a2-cf226b53fe86',
//       status: 'A',
//       position: 'P',
//       primary_position: 'SP',
//       first_name: 'Scott',
//       last_name: 'Blewett',
//       preferred_name: 'Scott',
//       jersey_number: '64',
//       full_name: 'Scott Blewett',
//       mlbam_id: '656240',
//       height: '78',
//       weight: '210',
//       throw_hand: 'R',
//       bat_hand: 'R',
//       high_school: 'Baker, Baldwinsville, NY',
//       birthdate: '1996-04-10',
//       birthstate: 'NY',
//       birthcountry: 'USA',
//       birthcity: 'Baldwinsville',
//       updated: '2019-02-08T19:38:55+00:00',
//       active: true
//     },
//     {
//       id: 'c63208a8-f0cb-4984-996e-79a9fdc2970a',
//       status: 'A',
//       position: 'P',
//       primary_position: 'RP',
//       first_name: 'Bradley',
//       last_name: 'Boxberger',
//       preferred_name: 'Brad',
//       jersey_number: '26',
//       full_name: 'Brad Boxberger',
//       mlbam_id: '502202',
//       height: '74',
//       weight: '205',
//       throw_hand: 'R',
//       bat_hand: 'R',
//       college: 'USC',
//       high_school: 'Foothill, North Tustin, CA',
//       birthdate: '1988-05-27',
//       birthstate: 'CA',
//       birthcountry: 'USA',
//       birthcity: 'Fullerton',
//       pro_debut: '2012-06-10',
//       updated: '2019-02-08T19:38:58+00:00',
//       active: true
//     },
//     {
//       id: 'b469052e-5b3b-42fa-bfe5-bdd91c6ccee5',
//       status: 'A',
//       position: 'P',
//       primary_position: 'RP',
//       first_name: 'Jacob',
//       last_name: 'Diekman',
//       preferred_name: 'Jake',
//       jersey_number: '40',
//       full_name: 'Jake Diekman',
//       mlbam_id: '518617',
//       height: '76',
//       weight: '200',
//       throw_hand: 'L',
//       bat_hand: 'L',
//       college: 'Cloud County CC, KS',
//       high_school: 'Wymore Southern, Wymore, NE',
//       birthdate: '1987-01-21',
//       birthstate: 'NE',
//       birthcountry: 'USA',
//       birthcity: 'Wymore',
//       pro_debut: '2012-05-15',
//       updated: '2019-02-20T14:46:41+00:00',
//       active: true
//     },
//     {
//       id: 'f9a0a01f-983d-4747-b545-04675281d914',
//       status: 'A',
//       position: 'P',
//       primary_position: 'SP',
//       first_name: 'Daniel',
//       last_name: 'Duffy',
//       preferred_name: 'Danny',
//       jersey_number: '41',
//       full_name: 'Danny Duffy',
//       mlbam_id: '518633',
//       height: '75',
//       weight: '205',
//       throw_hand: 'L',
//       bat_hand: 'L',
//       high_school: 'Cabrillo, Lompoc, CA',
//       birthdate: '1988-12-21',
//       birthstate: 'CA',
//       birthcountry: 'USA',
//       birthcity: 'Goleta',
//       pro_debut: '2011-05-18',
//       updated: '2019-01-30T21:59:17+00:00',
//       active: true
//     },
//     {
//       id: 'e83b0cac-dd0a-4764-8872-155abf7eea26',
//       status: 'A',
//       position: 'P',
//       primary_position: 'SP',
//       first_name: 'Christopher',
//       last_name: 'Ellis',
//       preferred_name: 'Chris',
//       jersey_number: '51',
//       full_name: 'Chris Ellis',
//       mlbam_id: '595939',
//       height: '77',
//       weight: '205',
//       throw_hand: 'R',
//       bat_hand: 'L',
//       college: 'MIssissippi',
//       high_school: 'Spain Park',
//       birthdate: '1992-09-22',
//       birthstate: 'AL',
//       birthcountry: 'USA',
//       birthcity: 'Birmingham',
//       updated: '2019-02-08T19:39:02+00:00',
//       active: true
//     },
//     {
//       id: '8c1c8a2a-c7ef-4538-ace1-318062c06957',
//       status: 'A',
//       position: 'P',
//       primary_position: 'SP',
//       first_name: 'Heath',
//       last_name: 'Fillmyer',
//       preferred_name: 'Heath',
//       jersey_number: '49',
//       full_name: 'Heath Fillmyer',
//       mlbam_id: '641571',
//       height: '73',
//       weight: '195',
//       throw_hand: 'R',
//       bat_hand: 'R',
//       college: 'Mercer County Community College',
//       high_school: 'Florence',
//       birthdate: '1994-05-16',
//       birthstate: 'NJ',
//       birthcountry: 'USA',
//       birthcity: 'Roebling',
//       pro_debut: '2018-06-24',
//       updated: '2019-01-30T22:02:11+00:00',
//       active: true
//     },
//     {
//       id: 'd0bcd76c-be9d-4e5b-949a-60e6320e51d5',
//       status: 'A',
//       position: 'P',
//       primary_position: 'RP',
//       first_name: 'Brian',
//       last_name: 'Flynn',
//       preferred_name: 'Brian',
//       jersey_number: '33',
//       full_name: 'Brian Flynn',
//       mlbam_id: '543169',
//       height: '79',
//       weight: '255',
//       throw_hand: 'L',
//       bat_hand: 'L',
//       college: 'Wichita State',
//       high_school: 'Owasso, OK',
//       birthdate: '1990-04-19',
//       birthstate: 'OK',
//       birthcountry: 'USA',
//       birthcity: 'Tulsa',
//       pro_debut: '2013-09-04',
//       updated: '2019-01-30T22:02:27+00:00',
//       active: true
//     },
//     {
//       id: '1a0fb3d9-41fc-4420-a141-caea9bcc7161',
//       status: 'A',
//       position: 'P',
//       primary_position: 'SP',
//       first_name: 'James',
//       last_name: 'Greene',
//       preferred_name: 'Conner',
//       jersey_number: '62',
//       full_name: 'Conner Greene',
//       mlbam_id: '641632',
//       height: '75',
//       weight: '185',
//       throw_hand: 'R',
//       bat_hand: 'R',
//       high_school: 'Santa Monica, CA',
//       birthdate: '1995-04-04',
//       birthstate: 'CA',
//       birthcountry: 'USA',
//       birthcity: 'Santa Monica',
//       updated: '2019-02-08T19:39:06+00:00',
//       active: true
//     },
//     {
//       id: 'a193c72e-e252-49c4-8ae5-2836039afda7',
//       status: 'D60',
//       position: 'P',
//       primary_position: 'SP',
//       first_name: 'Jesse',
//       last_name: 'Hahn',
//       preferred_name: 'Jesse',
//       jersey_number: '32',
//       full_name: 'Jesse Hahn',
//       mlbam_id: '534910',
//       height: '76',
//       weight: '215',
//       throw_hand: 'R',
//       bat_hand: 'R',
//       college: 'Virginia Tech',
//       high_school: 'Robert E. Fitch, Groton, CT',
//       birthdate: '1989-07-30',
//       birthstate: 'CT',
//       birthcountry: 'USA',
//       birthcity: 'Norwich',
//       pro_debut: '2014-06-03',
//       updated: '2019-02-20T14:49:45+00:00',
//       active: false,
//       dl60: true,
//       injuries: [
//         {
//           id: '305edc32-2a6e-4f2e-8d44-aad4839f1e97',
//           comment:
//             "The Kansas City Royals placed RHP Jesse Hahn on the 60-day disabled list as he recovers from Tommy JOhn surgery. He's not expected to be ready until June, according to Jeffrey Flanagan of MLB.com.",
//           desc: 'Elbow',
//           status: 'D60',
//           start_date: '2019-02-20',
//           update_date: '2019-02-20'
//         }
//       ]
//     },
//     {
//       id: '4fcc1c64-8cb6-4204-8f25-5a5f46cd0ae7',
//       status: 'A',
//       position: 'P',
//       primary_position: 'SP',
//       first_name: 'Arnaldo',
//       last_name: 'Hernandez',
//       preferred_name: 'Arnaldo',
//       jersey_number: '39',
//       full_name: 'Arnaldo Hernandez',
//       mlbam_id: '642511',
//       height: '72',
//       weight: '175',
//       throw_hand: 'R',
//       bat_hand: 'R',
//       birthdate: '1996-02-09',
//       birthcountry: 'VEN',
//       birthcity: 'San Felix',
//       updated: '2019-02-08T19:39:39+00:00',
//       active: true
//     },
//     {
//       id: '934c78d9-d33a-4ad0-9fbf-ffe6548d2783',
//       status: 'A',
//       position: 'P',
//       primary_position: 'RP',
//       first_name: 'Timothy',
//       last_name: 'Hill',
//       preferred_name: 'Tim',
//       jersey_number: '54',
//       full_name: 'Tim Hill',
//       mlbam_id: '657612',
//       height: '74',
//       weight: '200',
//       throw_hand: 'L',
//       bat_hand: 'R',
//       college: 'Bacone College',
//       high_school: 'Granada Hills',
//       birthdate: '1990-02-10',
//       birthstate: 'CA',
//       birthcountry: 'USA',
//       birthcity: 'Sylmar',
//       pro_debut: '2018-03-29',
//       updated: '2019-01-30T22:04:08+00:00',
//       active: true
//     },
//     {
//       id: '919d18a0-cd70-43c9-81f2-b96bf9e66a17',
//       status: 'A',
//       position: 'P',
//       primary_position: 'SP',
//       first_name: 'Jakob',
//       last_name: 'Junis',
//       preferred_name: 'Jake',
//       jersey_number: '65',
//       full_name: 'Jake Junis',
//       mlbam_id: '596001',
//       height: '74',
//       weight: '225',
//       throw_hand: 'R',
//       bat_hand: 'R',
//       high_school: 'Rock Falls (IL)',
//       birthdate: '1992-09-16',
//       birthstate: 'IL',
//       birthcountry: 'USA',
//       birthcity: 'Rock Falls',
//       pro_debut: '2017-04-12',
//       updated: '2018-07-21T18:18:13+00:00',
//       active: true
//     },
//     {
//       id: '12901252-d204-49f6-8af2-7446bf4b0a4f',
//       status: 'A',
//       position: 'P',
//       primary_position: 'SP',
//       first_name: 'Brad',
//       last_name: 'Keller',
//       preferred_name: 'Brad',
//       jersey_number: '56',
//       full_name: 'Brad Keller',
//       mlbam_id: '641745',
//       height: '77',
//       weight: '230',
//       throw_hand: 'R',
//       bat_hand: 'R',
//       high_school: 'Flowery Branch (GA)',
//       birthdate: '1995-07-27',
//       birthstate: 'GA',
//       birthcountry: 'USA',
//       birthcity: 'Flowery Branch',
//       pro_debut: '2018-03-29',
//       updated: '2018-05-30T17:19:11+00:00',
//       active: true
//     },
//     {
//       id: 'd9ed48ab-6740-411c-84b2-be4cc75b83c5',
//       status: 'A',
//       position: 'P',
//       primary_position: 'SP',
//       first_name: 'Ian',
//       last_name: 'Kennedy',
//       preferred_name: 'Ian',
//       jersey_number: '31',
//       full_name: 'Ian Kennedy',
//       mlbam_id: '453178',
//       height: '72',
//       weight: '205',
//       throw_hand: 'R',
//       bat_hand: 'R',
//       college: 'Southern California',
//       high_school: 'La Quinta, Huntington Beach, CA',
//       birthdate: '1984-12-19',
//       birthstate: 'CA',
//       birthcountry: 'USA',
//       birthcity: 'Huntington Beach',
//       pro_debut: '2007-09-01',
//       updated: '2019-01-30T22:05:21+00:00',
//       active: true
//     },
//     {
//       id: '32a615d1-9a88-4cd0-be2f-d8f1d731715e',
//       status: 'A',
//       position: 'P',
//       primary_position: 'SP',
//       first_name: 'Edward',
//       last_name: 'Lively',
//       preferred_name: 'Ben',
//       jersey_number: '48',
//       full_name: 'Ben Lively',
//       mlbam_id: '594902',
//       height: '76',
//       weight: '190',
//       throw_hand: 'R',
//       bat_hand: 'R',
//       college: 'Central Florida',
//       high_school: 'Gulf Breeze',
//       birthdate: '1992-03-05',
//       birthstate: 'FL',
//       birthcountry: 'USA',
//       birthcity: 'Pensacola',
//       pro_debut: '2017-06-03',
//       updated: '2018-09-08T01:32:11+00:00',
//       active: true
//     },
//     {
//       id: 'b9766398-e982-43a6-a3a0-f7f8e24061c6',
//       status: 'A',
//       position: 'P',
//       primary_position: 'SP',
//       first_name: 'Jorge',
//       last_name: 'Lopez',
//       preferred_name: 'Jorge',
//       jersey_number: '52',
//       full_name: 'Jorge Lopez',
//       mlbam_id: '605347',
//       height: '75',
//       weight: '195',
//       throw_hand: 'R',
//       bat_hand: 'R',
//       high_school: 'Caguas Military Academy ',
//       birthdate: '1993-02-10',
//       birthcountry: 'PRI',
//       birthcity: 'Cayey',
//       pro_debut: '2015-09-29',
//       updated: '2018-09-15T19:14:28+00:00',
//       active: true
//     },
//     {
//       id: '27a1dd02-5723-4108-a429-1d1d8fb69000',
//       status: 'A',
//       position: 'P',
//       primary_position: 'RP',
//       first_name: 'Kevin',
//       last_name: 'McCarthy',
//       preferred_name: 'Kevin',
//       jersey_number: '61',
//       full_name: 'Kevin McCarthy',
//       mlbam_id: '641838',
//       height: '75',
//       weight: '215',
//       throw_hand: 'R',
//       bat_hand: 'R',
//       college: 'Marist',
//       high_school: 'Kellenberg Memorial ',
//       birthdate: '1992-02-22',
//       birthstate: 'NY',
//       birthcountry: 'USA',
//       birthcity: 'Rockville Centre',
//       pro_debut: '2016-09-09',
//       updated: '2019-01-30T22:06:33+00:00',
//       active: true
//     },
//     {
//       id: '660bcefc-e3ef-4c52-bcaa-2055fddb6a4f',
//       status: 'A',
//       position: 'P',
//       primary_position: 'RP',
//       first_name: 'Samuel',
//       last_name: 'McWilliams',
//       preferred_name: 'Sam',
//       jersey_number: '52',
//       full_name: 'Sam McWilliams',
//       mlbam_id: '656726',
//       height: '79',
//       weight: '190',
//       throw_hand: 'R',
//       bat_hand: 'R',
//       high_school: 'Beech, Hendersonville, TN',
//       birthdate: '1995-09-04',
//       birthstate: 'FL',
//       birthcountry: 'USA',
//       birthcity: 'Orlando',
//       updated: '2019-02-08T19:39:47+00:00',
//       active: true
//     },
//     {
//       id: 'f8b4b146-daef-4b82-b5b8-198c4655b547',
//       status: 'A',
//       position: 'P',
//       primary_position: 'RP',
//       first_name: 'Christopher',
//       last_name: 'Newberry',
//       preferred_name: 'Jake',
//       jersey_number: '68',
//       full_name: 'Jake Newberry',
//       mlbam_id: '623470',
//       height: '74',
//       weight: '195',
//       throw_hand: 'R',
//       bat_hand: 'R',
//       high_school: 'Mira Mesa, San Diego, CA',
//       birthdate: '1994-11-20',
//       birthstate: 'CA',
//       birthcountry: 'USA',
//       birthcity: 'San Diego',
//       pro_debut: '2018-08-20',
//       updated: '2019-01-30T22:08:00+00:00',
//       active: true
//     },
//     {
//       id: '1019e26a-57a1-4480-aed5-843bab37154a',
//       status: 'A',
//       position: 'P',
//       primary_position: 'RP',
//       first_name: 'Trevor',
//       last_name: 'Oaks',
//       preferred_name: 'Trevor',
//       jersey_number: '34',
//       full_name: 'Trevor Oaks',
//       mlbam_id: '656805',
//       height: '75',
//       weight: '225',
//       throw_hand: 'R',
//       bat_hand: 'R',
//       college: 'California Baptist',
//       high_school: 'Woodcrest Christian',
//       birthdate: '1993-03-26',
//       birthstate: 'CA',
//       birthcountry: 'USA',
//       birthcity: 'Riverside',
//       pro_debut: '2018-04-28',
//       updated: '2019-01-30T22:08:17+00:00',
//       active: true
//     },
//     {
//       id: '0d8e671c-d03c-4024-9817-44b803833083',
//       status: 'A',
//       position: 'P',
//       primary_position: 'RP',
//       first_name: 'Wily',
//       last_name: 'Peralta',
//       preferred_name: 'Wily',
//       jersey_number: '43',
//       full_name: 'Wily Peralta',
//       mlbam_id: '503449',
//       height: '73',
//       weight: '255',
//       throw_hand: 'R',
//       bat_hand: 'R',
//       birthdate: '1989-05-08',
//       birthcountry: 'DOM',
//       birthcity: 'Samana',
//       pro_debut: '2012-04-22',
//       updated: '2019-01-30T22:08:53+00:00',
//       active: true
//     },
//     {
//       id: '3e007eed-c69d-4299-aacc-2d8516b07caf',
//       status: 'A',
//       position: 'P',
//       primary_position: 'RP',
//       first_name: 'Glenn',
//       last_name: 'Sparkman',
//       preferred_name: 'Glenn',
//       jersey_number: '57',
//       full_name: 'Glenn Sparkman',
//       mlbam_id: '642098',
//       height: '74',
//       weight: '210',
//       throw_hand: 'R',
//       bat_hand: 'B',
//       college: 'Wharton County Junior College',
//       high_school: 'Ganado',
//       birthdate: '1992-05-11',
//       birthstate: 'TX',
//       birthcountry: 'USA',
//       birthcity: 'Ganado',
//       pro_debut: '2017-06-30',
//       updated: '2018-09-04T18:43:49+00:00',
//       active: true
//     },
//     {
//       id: '337b2f91-7c1b-403f-9d80-7c5152b13e7e',
//       status: 'A',
//       position: 'P',
//       primary_position: 'RP',
//       first_name: 'Joshua',
//       last_name: 'Staumont',
//       preferred_name: 'Josh',
//       jersey_number: '63',
//       full_name: 'Josh Staumont',
//       mlbam_id: '622251',
//       height: '75',
//       weight: '200',
//       throw_hand: 'R',
//       bat_hand: 'R',
//       college: 'Azusa Pacific',
//       high_school: 'La Habra',
//       birthdate: '1993-12-21',
//       birthstate: 'CA',
//       birthcountry: 'USA',
//       birthcity: 'La Habra',
//       updated: '2019-02-08T19:40:09+00:00',
//       active: true
//     },
//     {
//       id: 'bdb882cc-ce44-4fba-8a28-fd3a4433541d',
//       status: 'A',
//       position: 'P',
//       primary_position: 'SP',
//       first_name: 'Kyle',
//       last_name: 'Zimmer',
//       preferred_name: 'Kyle',
//       jersey_number: '45',
//       full_name: 'Kyle Zimmer',
//       mlbam_id: '622092',
//       height: '75',
//       weight: '225',
//       throw_hand: 'R',
//       bat_hand: 'R',
//       college: 'San Francisco',
//       high_school: 'La Jolla',
//       birthdate: '1991-09-13',
//       birthstate: 'CA',
//       birthcountry: 'USA',
//       birthcity: 'San Francisco',
//       updated: '2019-02-08T19:40:13+00:00',
//       active: true
//     }
//   ],
//   _comment:
//     'Generation started @ 2019-02-23 21:39:00 UTC ended @ 2019-02-23 21:39:01 UTC'
// };
